// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependency

import (
	"wb/config"
	"wb/internal/config/database/postgre"
	"wb/internal/http/controllers"
	"wb/internal/routes"
)

// Injectors from wire.go:

// InitializeApp создает и инициализирует все зависимости приложения
func InitializeApp() (*App, error) {
	app := NewFiberApp()
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	database, err := postgre.NewDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	orderController := controllers.NewOrderController(database)
	router := routes.NewRouter(app, configConfig, database, orderController)
	dependencyApp := &App{
		FiberApp: app,
		Router:   router,
		Config:   configConfig,
	}
	return dependencyApp, nil
}
